POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlZ2lzdGVyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM0NzI5NjYxLCJ1c2VySWQiOjB9.ZFk4uhaXaMMSBAhqx8xQbhEZWtrGKlJ3lh4wJ33MqgU

{
    "name": "test event 4",
    "description": "another test event",
    "location": "test location",
    "dateTime": "2024-01-01T15:30:00.000Z"
}
