POST http://localhost:8080/events
content-type: application/json

{
    "name": "test event",
    "description": "another test event",
    "location": "test location",
    "dateTime": "2024-01-01T15:30:00.000Z"
}
