DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzQ3Mjg4MDAsInVzZXJJZCI6MH0.xlP_rDCXAiLUz3rS3w7OSvh--eJmY5jYgkIL3ZDY44s